# Generated by Django 6.0.3 on 2026-03-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_vencimento_aso',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento do ASO (Exame)'),
        ),
    ]
