# Generated by Django 6.0.3 on 2026-03-12 17:22

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_data_vencimento_aso'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', accounts.models.MeuUsuarioManager()),
            ],
        ),
    ]
