# Generated by Django 6.0.3 on 2026-03-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do EPI')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('tamanho', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho')),
                ('ca_numero', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número do CA')),
                ('ca_validade', models.DateField(blank=True, null=True, verbose_name='Validade do CA')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no Sistema')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
