# Generated by Django 6.0.3 on 2026-03-10 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('status', models.CharField(choices=[('EM_USO', 'Em Uso (Com o funcionário)'), ('DEVOLVIDO', 'Devolvido (Voltou pro estoque)'), ('DESCARTADO', 'Descartado / Danificado'), ('PERDIDO', 'Perdido')], default='EM_USO', max_length=20, verbose_name='Status da Entrega')),
                ('data_entrega', models.DateTimeField(auto_now_add=True, verbose_name='Data da Entrega')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador (Quem recebe)')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entregas', to='inventory.epi', verbose_name='EPI')),
            ],
        ),
    ]
