# Generated by Django 6.0.3 on 2026-03-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='epi',
            name='vida_util_dias',
            field=models.PositiveIntegerField(default=0, help_text='Quantos dias este EPI dura antes de precisar ser trocado? (Deixe 0 se não houver validade)', verbose_name='Vida Útil (Dias)'),
        ),
    ]
