# Generated by Django 6.0.3 on 2026-03-12 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_epi_vida_util_dias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador (Beneficiário)'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Devolução/Encerramento'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='epi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entregas', to='inventory.epi', verbose_name='Equipamento (EPI)'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações de Campo'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade Movimentada'),
        ),
        migrations.AlterField(
            model_name='epi',
            name='vida_util_dias',
            field=models.PositiveIntegerField(default=0, help_text='Estimativa de durabilidade para fins de troca preventiva.', verbose_name='Vida Útil (Dias)'),
        ),
    ]
